language: python

python:
    - "2.7"
    - "3.4"

env:
    - DJANGO=1.6
    - DJANGO=1.7

install:
    - pip install -q django==$DJANGO --use-mirrors
    - pip install -q django-nose>=1.2 --use-mirrors
    - pip install -q -e . --use-mirrors

script:
    - python testproject/manage.py test

