language: python

python:
    - "2.7"
    - "3.4"

env:
    - DJANGO=1.6
    - DJANGO=1.7
    - DJANGO=1.8

install:
    - pip install -q django==$DJANGO
    - pip install -q -r requirements.txt
    - pip install -q -e .
    - pip install -q -r requirements-dev.txt

script:
    - cd testproject && python manage.py test

